### ISSUE TITLE
Proper namespace

### ISSUE THREAD

**Issue by szepeviktor** [cliffordp/cliff-wp-plugin-boilerplate#96]
Please consider using proper namespaces.

```php
namespace Company\WordPress\PluginName;

// e.g.

namespace AcmeLabs\WordPress\Mnemonic;
// then
namespace AcmeLabs\WordPress\Mnemonic\Frontend;
```

What do you think?

**Comment by cliffordp** [comment]
Re: https://www.php-fig.org/psr/psr-4/

I've read and researched and while I don't disagree with your format, I don't know that this boilerplate's use of the plugin name as the top-level "vendor namespace" is incorrect.

Best I understand, it's ideal if the vendor namespace is unique among all PHP packages in the world, but there's often "Acme Labs Corp." and "Acme Labs LLC" and "AcmeLabs" as the top-level is likely less unique than the plugin name itself.

Of course, the user of the boilerplate is free to do as they wish with the search-replace that's currently required to use the template.

**Comment by szepeviktor** [comment]
Excuse me but `AcmeLabs\WordPress\Mnemonic` seem more unique than `Mnemonic`.

**Comment by cliffordp** [comment]
I was trying to communicate that, in my opinion, `AcmeLabs` as the top-level vendor namespace is less likely to be unique worldwide than having `ThePluginThatDoesThisThingName` as the top-level namespace -- especially since the plugin slug should be unique from https://WordPress.org/plugins (even if not published there) because then the WordPress auto updater will confuse it for one from the public repo... and experts in namespacing would of course be able to accomplish their preferences.

Thanks for asking the question :)

**Comment by szepeviktor** [comment]
Okay, let's say two companies use the `AcmeLabs` top namespace. There is 0% chance that those two publish plugins with the very same namespave `AcmeLabs\WordPress\Mnemonic`.

An I see a contradiction in the classic OOP and the WordPress ecosystem.
I clearly follow OOP standards, best practices as everything WordPress targets non-professionals.

**Comment by szepeviktor** [comment]
Take this very good example!

![kép](https://user-images.githubusercontent.com/952007/102679109-76032f80-41ad-11eb-981a-a1a7b7b2729e.png)

saying everyone should use the PHP4 long syntax because "those with vision difficulties" and "beginners".

**Comment by cliffordp** [comment]
Thanks for sharing today.
